# -----------------------------------------------------------------------#
# /!\                     DRIVER PROPERTIES                          /!\ #
# -----------------------------------------------------------------------#


# -----------------------------------------------------------------------#
# /!\                      URL HOME                        /!\ #
# -----------------------------------------------------------------------#
erudaxis.url = https://staging.erudaxis.com/

# -----------------------------------------------------------------------#
# /!\\                     URL CREDENTIALS                        /!\\ #
# -----------------------------------------------------------------------#
erudaxis.login=ayoubzitouni299@gmail.com
erudaxis.password=Ayoub@2026!